development:
  adapter: mysql
  encoding: utf8
  database: demo_development
  host: 127.0.0.1
  username: 'root'
  password: '27361906'
  port: 3306

test:
  adapter: mysql
  encoding: utf8
  database: demo_test
  host: 127.0.0.1
  username: 'root'
  password: '27361906'
  port: 3306
  
production:
  adapter: mysql
  encoding: utf8
  database: demo_production
  host: 127.0.0.1
  username: 'root'
  password: '27361906'
  port: 3306